- .changelogs/1.0.0/16_add_rebalancing_by_assigned_resources.yml
- README.md
- docs/02_Configuration.md
- proxlb
- proxlb.conf
feature: Add option to rebalance VMs by their assigned resources. [#16]
** WIP **
Rebalance VMs based on their assigned resources that can potentially be used. This might make sense to ensure the resources are fully available for the VM and to avoid overprovisioning of nodes in general. 
Fixes: #16
> feature: Add option to rebalance VMs by their assigned resources. [#16]

- .changelogs/1.0.0/10_add_container_support.yml
- .changelogs/1.0.0/27_add_container_lxc_support.yml
- README.md
- proxlb
feature(core): Add support for LXC/Container to be rebalanced.
Add support for Proxmox LXC (container) to be rebalanced across the nodes in a cluster.
Should work technically but needs further testing. Also requires a new state in the output json, where the VM/CT type should be flagged.
Example output of migrated VMs (type: `vm`):
```
VM   Current Node   Rebalanced Node   VM Type
test06-gyptazy01         virt01            virt02        vm
test02         virt01            virt03        vm
test04         virt01            virt02        vm
```
Example output of migrated CTs (type: `ct`):
```
VM   Current Node   Rebalanced Node   VM Type
gyp02         virt01            virt02        ct
gyp01         virt01            virt03        ct
```
Example output of migrated resources (type `all`):
``` …
```
> feature(core): Add support for LXC/Container to be rebalanced.

- CONTRIBUTING.md
- README.md
- docs/03_FAQ.md
docs: Update the docs
Add more content to the docs, add the contributing file and also mention the new chat and how ProxLB works.
Fixes: #30
> docs: Update the docs

- proxlb
fix: Rebalance CT function including reboot
Rebalances containers to new host nodes.
ProxLB Output:
```
VM   Current Node   Rebalanced Node   VM Type
gyp01         virt01            virt03        ct
gyp02         virt01            virt02        ct
<6> ProxLB: Info: [post-validations]: All post-validations succeeded.
<6> ProxLB: Info: [daemon]: Not running in daemon mode. Quitting.
```
Task Log Proxmox:
Fixes: #27
Fixes: #29
> fix: Rebalance CT function including reboot

- .changelogs/1.0.0/29_add_option_rebalance_by_node_percent.yml
- README.md
- proxlb
feature: Add new mode_option to rebalance by node's bytes or percent.
This adds the requested (by @ewenlau) option to to rebalance by the node's free resources in percent instead of bytes. The operation mode for this can be changed by the newly introduced option `mode_option` which is by default `bytes`.
A user can define this by setting `bytes` or `percent`.
This PR also adds a function to validate if there are objects of type VM or CT to rebalance to avoid raising a stack trace when no objects are present in a cluster (e.g. freshly installed cluster).
Fixes: #29
> feature: Add new mode_option to rebalance by node's bytes or percent.

- .changelogs/1.1.0/41_add_option_run_migration_parallel_or_sequential.yml
- .changelogs/1.1.0/release_meta.yml
- README.md
- proxlb
feature: Add option to run migrations in parallel or sequentially
The newly introduced option parameter `parallel_migrations` (default: 1 [True] == enabled) provides the possibility to define if migrations should be performed in parallel. If this is set to `0`, migration will be performed sequentially. During this, the API will be queried until the job is completed for the migration before starting the next migration.
Test:
```
<6> ProxLB: Info: [rebalancing-executor]: Rebalancing VM test09-fat02 from node virt01 to node virt03.
<6> ProxLB: Info: [rebalancing-executor]: Rebalancing will be performed sequentially.
<6> ProxLB: Info: [job-status-getter]: Getting job status for job UPID:virt01:0009E042:00E90932:66AF1E6C:qmigrate:108:root@pam:.
<6> ProxLB: Info: [job-status-getter]: {'pid': …
```
> feature: Add option to run migrations in parallel or sequentially

- .changelogs/1.1.0/40_add_option_to_run_only_on_cluster_master_node.yml
- README.md
- proxlb
feature: Add option to run ProxLB only on the Proxmox's master node in the cluster.
Running on a different node:
```
<6> ProxLB: Info: [logger]: Logger verbosity got updated to: INFO.
<4> ProxLB: Warning: [api-connection]: API connection does not verify SSL certificate.
<6> ProxLB: Info: [api-connection]: API connection succeeded to host: 10.10.10.211.
<6> ProxLB: Info: [cluster-master-getter]: Getting master node from cluster.
<6> ProxLB: Info: [cluster-master-getter]: Master node: virt03
<6> ProxLB: Info: [cluster-master-validator]: Node executor hostname is: dev-nfs01
<6> ProxLB: Info: [cluster-master-validator]: dev-nfs01 is not the cluster master (virt03).
<6> ProxLB: Info: [daemon]: Running in daemon mode. Next run in 24 hours.
```
Running on the master node:
```
<6> ProxLB: Info: …
```
> feature: Add option to run ProxLB only on the Proxmox's master node in the cluster.

- .changelogs/1.1.0/45_fix_daemon_timer.yml
- proxlb
fix: Fix daemon timer to use hours instead of minutes.
The option within the configuration file is defined in hours but it gets passed in the code as seconds where it simply gets multiplied by 60. As a result, we're just getting minutes instead of hours and we need to multiply it by additional 60 to reach hours.
Reported by: @mater-345
Fixes: #45
> fix: Fix daemon timer to use hours instead of minutes.

- .changelogs/1.0.3/53_code_improvements.yml
- .changelogs/1.0.3/8_add_best_next_node_for_placement.yml
- .changelogs/1.0.3/bug_fix_cluster_master_only.yml
- .changelogs/1.0.3/release_meta.yml
- README.md
- proxlb
- proxlb.conf
feature: Add cli arg (-b) to return the best next node for VM placement.
- Added cli arg `-b` to return the next best node for next VM/CT placement. [#8]
- Added convert function to cast all bool alike options from configparser to bools. [#53]
- Added config parser options for future features. [#53]
- Added a config versio schema that must be supported by ProxLB. [#53]
- Improved the underlying code base for future implementations. [#53]
Fixes: #8
Fixes: #53
> feature: Add cli arg (-b) to return the best next node for VM placement.

- .changelogs/1.0.3/51_add_storage_balancing.yml
- .changelogs/1.0.3/53_code_improvements.yml
- .changelogs/1.0.3/60_allow_api_hosts_to_be_given_as_an_optional_list.yml
- .changelogs/1.0.3/8_add_best_next_node_for_placement.yml
- README.md
- docs/03_FAQ.md
- proxlb
* feature: Add storage balancing function.
* feature: Add feature to allow the API hosts being provided as a comma separated list.
This PR adds the feature to also allow storage balancing and supports VMs and CTs. It also supports multiple disks assigned to VMs and CTs. In the first iteration it can only balance by `disk_space`. I'm currently still evaluating to implement also an additional balancing method by `disk_io`.
```
<6> ProxLB: Info: [storage-balanciness-validation]: Getting most free storage volume by disk size.
<6> ProxLB: Info: [storage-balanciness-validation]: Validating storage: net-nfs01 for balanciness for usage with: disk_space.
<6> ProxLB: Info: [storage-balanciness-validation]: Storage: net-nfs01 with values: {'name': 'net-nfs01', 'total': 314915684352, 'used': …
```
> feature: Add storage balancing function.

- .changelogs/1.0.3/64_improve_error_handling_and_validations.yml
- README.md
- docs/02_Configuration.md
- proxlb
fix: Adjusted and improved the general error handling.
Fixes: #64
> fix: Adjusted and improved the general error handling.

- .changelogs/1.0.3/67_fix_anti_affinity_rules.yml
- .changelogs/1.0.3/68_adjust_logging_ha_services.yml
- .changelogs/1.0.3/71_fix_ignore_vm_node_handling_if_unset.yml
- proxlb
fix: Fix anti-affinity rules not evaluating a new and different node correctly.
This PR fixes an issue where a new and different node was not correctly evaluated when working with anti-affinity rules. It also applies and adds some more logging and fixes wrong logging options that were previously defined.
```
<6> ProxLB: Info: [rebalancing-tags-group-exclude]: Rebalancing of VM test03-small is needed due to anti-affinity group policy.
<6> ProxLB: Info: [random-node-getter]: New random node pmx01 evaluated in run 1.
<6> ProxLB: Info: [random-node-getter]: New random node pmx03 evaluated in run 2.
<6> ProxLB: Info: [random-node-getter]: New random node pmx01 evaluated in run 3.
<6> ProxLB: Info: [random-node-getter]: New random node pmx01 evaluated in run 4.
<6> ProxLB: Info: …
```
> fix: Fix anti-affinity rules not evaluating a new and different node correctly

- .changelogs/1.0.3/74_fix_documentation_master_only.yml
- README.md
docs: Fix documentation for the master_only parameter placed in the wrong config section.
Fixes: #74
> docs: Fix documentation for the master_only parameter placed in the wrong config section.

- .changelogs/1.0.4/81_documentation_infrastrucutre.yml
- README.md
fix(docs): Fix outdated documentation regarding the infrastructure.
Fix the documentation how to use and obtain `ProxLB` from the new infrastructure after changing the base domain.
Fixes: [#81]
> fix(docs): Fix outdated documentation regarding the infrastructure.

- .changelogs/1.0.4/58_add_maintenance_mode.yml
- README.md
- proxlb
- proxlb.conf
feature: Add maintenance mode to evacuate a node and move workloads for other nodes in the cluster.
This PR adds a maintenance mode to ProxLB which evacuates all workloads of type VM and CT to other nodes in cluster. One or multiple nodes can be defined at the same time.
This feature can be used in two different ways. 
It can be passed as a comma separated list when invoking proxlb. Example:
```
./proxlb -m virt01,virt02
```
It can also be defined in the proxlb.conf file by adding the following line within the `vm_balancing` section:
```
maintenance_nodes: virt01,virt02
```
You can also combine both ones, the nodes will be merged.
Fixes: #58
Fixes: #84
> feature: Add maintenance mode to evacuate a node and move workloads for other nodes in the cluster.

- .changelogs/1.0.4/89_add_version_output.yml
- README.md
- proxlb
feature: Add version output as cli arg
Fixes: #89
> feature: Add version output as cli arg

- .changelogs/1.0.4/75_fix_cpu_balancing.yml
- proxlb
fix: Fix CPU balancing where calculations are done in float instead of int.
This PR fixes handling of CPU based balancing by avoiding rounding issues treating the values in float instead of integer.
Thanks to @glitchvern by providing the patch and testing in #75.
Patch also passed by test runs, so we're good to go and may include this into the upcoming 1.0.4 release.
By: @glitchvern
Fixes: #75
> fix: Fix CPU balancing where calculations are done in float instead of int.

- .changelogs/1.0.5/106_fix_maintenance_mode_compare_str_list.yml
- .changelogs/1.0.5/107_fix_offline_node_eval.yml
- proxlb
fix: Fix offline node evaluation & maintenance compare of different type objects
- Fix node (and its objects) evaluation when not reachable (e.g., maintenance).
- Fix evaluation of maintenance mode where comparing list & string resulted in a crash (by @glitchvern).
- Set ProxLB version to 1.0.5b
Fixes: #106
Fixes: #107
Contributed-by: @glitchvern
> fix: Fix offline node evaluation & maintenance compare of different type objects

- .changelogs/1.0.5/113_fix_migration_from_local_disk.yml
- proxlb
Add parameter `with-local-disks=1` to allow migration from local disks.
Otherwise rebalancing fails with error:
```
2024-10-18 10:09:38 can't migrate local disk 'local-ssd:104/vm-104-disk-0.qcow2': can't live migrate attached local disks without with-local-disks option
```
> Allow migration from local disks

- .changelogs/1.0.6/115_fix_daemon_scheduler_bool_time_fix.yml
- proxlb
fix: Fix that a scheduler time definition of 1 (int) gets wrongly interpreted as a bool.
Fixes: #115
> fix: Fix that a scheduler time definition of 1 (int) gets wrongly interpreted as a bool.

- .changelogs/1.0.6/119_fix_maintenance_mode_cli_and_config.yml
- proxlb
Fix maintenance mode when using cli arg and config mode by using the merged list.
Sponsored-by: @CartCaved
Fixes: #119
> Fix maintenance mode when using cli arg and config mode by using the merged list.

- Dockerfile
- docker-compose.yml
Used a smaller base in the dockerfile with python already installed. Only copied over the files and installed requirements instead of the whole python venv and apt updates. This way, I reduced the build time from ~3 minutes to just ~30 seconds (on my environment). 
Added a docker compose file which builds the Dockerfile locally and also attaches the proxlb.conf file.
> feat: optimize Dockerfile, create docker-compose with build

- .changelogs/1.0.7/135_fix_systemd_service_install_target.yml
- docs/01_Installation.md
- packaging/proxlb.service
Adds network requirements and install target to systemd service file.
Fixes #135
> fix: systemd service install target

- .changelogs/1.1.0/125-add-proxmox-api-authentication-support.yml
- README.md
- config/proxlb_example.yaml
- proxlb/utils/proxmox_api.py
feature: Add Proxmox API token authentication
Add support to ProxLB to also support the native Proxmox API authentication by using API tokens instead of username and password.
Fixes: #125
> feature: Add Proxmox API token authentication

- README.md
- config/proxlb_example.yaml
- proxlb/models/calculations.py
adjustment: Rename param `force` to `enforce_affinity`
* This change should make the parameter's intention more clear
Fixes: #146
> adjustment: Rename param `force` to `enforce_affinity`

- .changelogs/1.1.0/137_fix_systemd_unit_file.yml
- service/proxlb.service
fix: Fix the systemd unit file to start after the pveproxy daemon
Fixed-by: @robertdahlem
Fixes: #137
Fixes: #155
> fix: Fix the systemd unit file to start after the pveproxy daemon

- proxlb/main.py
- proxlb/models/calculations.py
- proxlb/utils/helper.py
fix: Add JSON output again
When passing `-j` a json output will be printed to stdout. This looks like:
```
% python3 proxlb/main.py -c ../proxlb.yaml -d -j    
SSL certificate validation to host 10.66.66.66 is deactivated.
Guest balancing is required. Highest value: 12.68458927312864, lowest value: 5.493756799142955 balanced by memory and used.
Node: cbc-kvm16 already got used for anti-affinity group:: plb_anti_affinity_harv. (Tried for guest: test-xn02)
{
"nodes": {
"test-c66": {
"name": "test-c66",
"maintenance": false,
"cpu_total": 48,
"cpu_assigned": 28,
"cpu_used": 0.03950707090217665,
"cpu_free": 46.88357655579746,
"cpu_assigned_percent": 58.333333333333336,
"cpu_free_percent": 97.67411782457805,
"cpu_used_percent": 0.08230639771286802,
"memory_total": 540915605504, …
```
> fix: Add JSON output again

- .changelogs/1.1.1/163_fix_ignore_vm_tag.yml
- .changelogs/1.1.1/165_improve_logging_servity.yml
- .changelogs/1.1.1/release_meta.yml
- proxlb/models/balancing.py
- proxlb/models/calculations.py
fix: Fix tag evluation for VMs for being ignored for further balancing
```
SSL certificate validation to host 10.11.11.11 is deactivated.
Balancing: Guest dummy01 rebalanced.
Balancing: Guest dummy04 is ignored and will not be rebalanced.
Balancing: Guest dummy02 rebalanced.
```
Fixes: #163
Fixes: #165
> fix: Fix tag evluation for VMs for being ignored for further balancing

- .changelogs/1.1.1/174_honor_balancing_activation_value.yml
- proxlb/main.py
fix: Honor the value when balancing should not be performed and stop balancing.
Fixes: #174
> fix: Honor the value when balancing should not be performed and stop balancing.

- .changelogs/1.1.1/187_allow_use_of_minutes_instead_of_hours.yml
- proxlb/utils/helper.py
Allow use of minutes instead of hours.
Also, validate the field format in the config file is minutes or hours.
fixes #187
> fix: allow use of minutes instead of hours

- .changelogs/1.1.1/185-logging-handler-for-no-systemd-integration.yml
- proxlb/utils/logger.py
Add a logging handler for when there is no systemd integration like inside a container.
I'm not sure if this is the best way to do this or not.
fixes: #185
> fix: logging handler for no systemd integration

- .changelogs/1.1.1/195_set_cpu_used_to_cpu_usage_times_core_count.yml
- proxlb/models/guests.py
- proxlb/models/nodes.py
Multiplying the cpu usage from the proxmox api by the total cores from the proxmox api gives numbers that can be added/subtracted as guests move from one node to another and then nodes compared to one another.
fixes: #195
> fix: set cpu_used to be cpu usage times number of cpu cores

- .changelogs/1.1.1/197_remove_hard_coded_memory_usage_from_lowest_usage_node.yml
- proxlb/models/calculations.py
Use method and mode specified in configuration to calculate lowest_usage_node.
By itself this change does little but combined with pull request #196 results in better balancing.
> fix: Use method/mode in configuration to calculate lowest_usage_node

- README.md
With 1.1.0, the default configuration file changed from proxlb.conf to proxlb.yaml but the README was not fully updated.
> Fix default configuration file path in README.md

- .changelogs/1.1.1/200_requery_zero_guest_cpu_used.yml
- proxlb/models/guests.py
Requery a guest if that running guest reports 0 cpu usage. Even an idle guest should have some small amount of cpu usage.
This one is a bit tighter than the last pull request.  Here we only requery the guests that have 0 percent cpu usage instead of requerying all the guests on a node.  We also only sleep for 1 second instead of 10 seconds.  Some of the 0 percent cpu usage guests sometimes have to be requeried multiple times and others get cpu usage on the first requery.  This results in more sleeps of shorter duration than the last pull request.  This still results in some delay between when the nodes are queried and when the guests are actually rebalanced.  A sufficiently long delay could allow a manual migration to be started and completed followed by ProxLB attempting to move the …
> fix: Requery a guest if that running guest reports 0 cpu usage

- .changelogs/1.1.2/137_fix_systemd_unit_file.yml
- service/proxlb.service
fix: Adjust the systemd unit file to run after the network target on non PVE nodes
Fixes: #137
> fix: Adjust the systemd unit file to run after the network target on non PVE nodes

- .changelogs/1.1.2/222_fix_force_type_cast_cpu_metrics_to_int.yml
- proxlb/models/calculations.py
- proxlb/models/guests.py
fix: Force type cast guest cpu count to int where in some corner cases a str got returned.
In #222 @raymand211092 reported a bug where we might get a string of `cpu_total` instead of an integer when obtaining the resources from the api.
```
Resources of Guest guest1 (type CT) added: {'name': 'guest1', 'cpu_total': '1', 'cpu_used': 0,
Resources of Guest guest2 (type CT) added: {'name': 'guest2', 'cpu_total': 2, 'cpu_>
```
This fails later when calculating the metrics. As a result, the cpu count gets force type casted to integer. This is strange, becasue according to the API (https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc) it should return a number (int).
Fixes: #222
> fix: Force type cast guest cpu count to int where in some corner cases a str got returned.

- .changelogs/1.1.3/94_cpu_balancing_use_avg_instead_current_consumption.yml
- proxlb/models/guests.py
feature:  Use the average CPU consumption of a guest within the last 60 minutes instead of the current CPU usage
- Using the current CPU consumption of a guest object is too volatile and does not represent the real usage. Therefore, we use the average consumption of the cpu values within the last 60 minutes.
Thanks-to: @philslab-ninja
Fixes: #94
> feature:  Use the average CPU consumption of a guest within the last 60 minutes instead of the current CPU usage

- .changelogs/1.1.5/260_allow_custom_api_ports.yml
- proxlb/utils/helper.py
- proxlb/utils/proxmox_api.py
feature: Allow custom (instead of static tcp/8006) API ports for API hosts
```
2025-07-08 08:06:52,585 - ProxLB - DEBUG - Starting: api_connect_get_hosts.
2025-07-08 08:06:52,585 - ProxLB - DEBUG - Starting: test_api_proxmox_host.
2025-07-08 08:06:52,585 - ProxLB - DEBUG - API host uses a custom port: host: lb.gyptazy.de with port tcp/443.
2025-07-08 08:06:52,836 - ProxLB - DEBUG - lb.gyptazy.de is type ipv4.
2025-07-08 08:06:52,837 - ProxLB - DEBUG - Starting: test_api_proxmox_host_ipv4.
2025-07-08 08:06:52,837 - ProxLB - WARNING - Warning: Host lb.gyptazy.de ran into a timeout when connecting on IPv4 for tcp/443.
2025-07-08 08:06:52,889 - ProxLB - DEBUG - Host lb.gyptazy.de is reachable on IPv4 for tcp/443.
2025-07-08 08:06:52,889 - ProxLB - WARNING - SSL certificate validation to host …
```
> feature: Allow custom (instead of static tcp/8006) API ports for API hosts

- .changelogs/1.1.6/291_fix_stack_trace_no_user_permissions_testing.yml
- proxlb/utils/proxmox_api.py
fix(proxmox-api): Fix stacktrace output when validating permissions on non existing users in Proxmox
Fixes: #291
We will now get a clearer error message like:
```
2025-08-25 07:50:00,119 - ProxLB - DEBUG - Finished: api_connect.
2025-08-25 07:50:00,119 - ProxLB - DEBUG - Starting: test_api_user_permissions.
2025-08-25 07:50:03,393 - ProxLB - ERROR - Authentication to Proxmox API not possible: User not known
```
> fix(proxmox-api): Fix stacktrace output when validating permissions on non existing users in Proxmox

- .changelogs/1.1.6/290_validate_user_token_syntax.yml
- proxlb/utils/proxmox_api.py
feature: Add validation for provided API user token id to avoid confusions
Fixes: #290
It now provides a more sane error message like:
```
2025-08-25 08:05:55,542 - ProxLB - DEBUG - Starting: api_connect.
2025-08-25 08:05:55,542 - ProxLB - DEBUG - Starting: validate_config.
2025-08-25 08:05:55,542 - ProxLB - ERROR - Wrong user/token format defined. User and token id must be splitted! Please see: https://github.com/gyptazy/ProxLB/blob/main/docs/03_configuration.md#required-permissions-for-a-user
```
> feature: Add validation for provided API user token id to avoid confusions

- .changelogs/1.1.6/296_fix_validate_node_presence_when_pinning_guests.yml
- proxlb/models/guests.py
- proxlb/models/tags.py
- proxlb/utils/helper.py
fix: Validate for node presence when pinning guests to avoid crashing
Fixes: #296
Fixes: #271
> fix: Validate for node presence when pinning guests to avoid crashing

- .changelogs/1.1.7/310_guest-object-names-not-being-evaluated-in-log.yml
- proxlb/models/balancing.py
fix: Fix guest object names are not being evaluated in debug log.
Fixes: #310
> fix: Fix guest object names are not being evaluated in debug log.
