.changelogs/1.0.0/3_create_grouping_include_feature.yml
.changelogs/1.0.0/4_create_grouping_exclude_feature.yml
.changelogs/1.0.0/7_ignore_vm_by_tag_proxlb_ignore_vm.yml
.changelogs/1.0.0/7_ignore_vms_by_wildcard.yml
.changelogs/1.0.0/release_meta.yml
README.md
docs/02_Configuration.md
proxlb

feature(tags): Add tag evaluation to provide new features:
* Bundle multiple VMs by tag to be relocated together [#3]
* Ensure by tag that VMs will not be reloccated to the same node [#5]
* Ignore VMs from being relocated by tag [#7] (req. by @daanbosch)
* Ignore VMs from being relocated by a wildcard pattern [#7] (req. by @daanbosch)
Note:
Still WIP - just a draft PR.
Fixes: #3
Fixes: #5
Fixes: #7

feature(tags): Add tag evaluation to provide new features

---

.changelogs/1.0.0/6_add_dry_run_support.yml
README.md
proxlb

feature: Add dry-run support to see what kind of rebalancing would be done. [#6]
* Add new cli param: -d for dry-run: Prints movements to cli
* Add new cli param: -j for json: Prints movement as a json to cli
Fixes: #6

feature: Add dry-run support to see what kind of rebalancing would be done

---

.changelogs/1.0.0/17-add-configurable-log-verbosity.yml
README.md
proxlb
proxlb.conf

feature(logging): Add configurable log verbosity. [#17]
With the new param `log_verbosity` which can be defined in the config file, the log verbosity can now be defined by using `INFO`, `WARNING` or `CRITICAL` (default).

feature(logging): Add configurable log verbosity. [#17]

---

README.md

docs: Add section for downloads (pkgs, repo, container image)
Fixes: #36

docs: Add section for downloads (pkgs, repo, container image)

---

.changelogs/1.0.4/91_make_api_timeout_configureable.yml
README.md
proxlb

feature: Add feature to make API timeout configureable
Fixes: #91

feature: Add feature to make API timeout configureable

---

.changelogs/1.0.5/104_docs_bool_adjustment.yml
.changelogs/1.0.5/release_meta.yml
CONTRIBUTING.md
README.md

fix(docs): Change docs to make bool usage in configs more clear.
Fixes: #104

fix(docs): Change docs to make bool usage in configs more clear.

---

README.md
proxlb/main.py
proxlb/models/balancing.py
proxlb/models/calculations.py
proxlb/models/groups.py
proxlb/models/guests.py
proxlb/models/nodes.py
proxlb/models/tags.py
proxlb/utils/cli_parser.py
proxlb/utils/config_parser.py
proxlb/utils/helper.py
proxlb/utils/logger.py
proxlb/utils/proxmox_api.py
proxlb/utils/version.py

enhancement: Adjust license information, adjust class/func descriptions

enhancement: Adjust license information, adjust class/func descriptions

---

Dockerfile

* Also switch from Debian image to Alpine image

feature: Add Dockerfile to create container image

---

docs/03_configuration.md
proxlb/utils/proxmox_api.py

fix: Fix mutal exclusive authentication based on secrets.
Fixes: #142

fix: Fix mutal exclusive authentication based on secrets.

---

Dockerfile

fixed path to python3 binary
#170

fix: path correction for docker entrypoint

---

.changelogs/1.1.1/171_set_correct_python_path_docker_image.yml

changelog: Add changelog for: Fix Python 3 path for Docker entrypoint
Sponsored-by: @crandler
Fixes: #170
Fixes: #171

changelog: Add changelog for: Fix Python 3 path for Docker entrypoint

---

docs/03_configuration.md

docs: Adjust docs regarding API Token and privilege separation.
Fixes: #164

docs: Adjust docs regarding API Token and privilege separation.

---

.changelogs/1.1.1/168_add_more_flexible_schedules.yml
.changelogs/1.1.1/174_honor_balancing_activation_value.yml
.changelogs/1.1.1/176_change_turn_daemon_mode_on_default.yml
.changelogs/1.1.1/180_change_default_balancing_to_used_instead_assigned.yml
README.md
config/proxlb_example.yaml

change: Change the default banalcing mode to used instead of assigned.
Fixes: #180

change: Change the default banalcing mode to used instead of assigned.

---

.changelogs/1.1.1/184_validate_for_sufficient_user_permissions.yml
proxlb/utils/proxmox_api.py

Feature: Add validation for the minimum required permissions of a user in Proxmox.
Fixes: #184

Feature: Add validation for the minimum required permissions of a user in Proxmox.

---

README.md
docs/03_configuration.md
proxlb/models/balancing.py
proxlb/models/calculations.py
proxlb/models/tags.py
proxlb/utils/proxmox_api.py

s/connectoing/connecting/
s/furhter/further/
s/interating/iterating/
s/ist/is/
s/maintence/maintenance/
s/performt/performed/
s/ressources/resources/
s/sucessfully/successfully/
s/the the/the/
s/timout/timeout/
s/wether/whether/

Minor typo fixes

---

.changelogs/1.1.1/185-logging-handler-for-no-systemd-integration.yml
.changelogs/1.1.1/187_allow_use_of_minutes_instead_of_hours.yml
proxlb/utils/logger.py

tecdebt: Improve logging handler creation
Fixes: #185

tecdebt: Improve logging handler creation

---

README.md
docs/03_configuration.md

docs: Add documentation about ignore guests such like VMs or CTs.

---

.changelogs/1.1.2/218_add_1_to_one_relationship_guest_node_pinning.yml
README.md
docs/03_configuration.md
proxlb/models/calculations.py
proxlb/models/guests.py
proxlb/models/tags.py

feature: Add possibility to pin guests to a specific hypervisor node.
Fixes: #218

feature: Add possibility to pin guests to a specific hypervisor node.

---

.changelogs/1.1.2/157_add_proxmox_api_retry_mechanism.yml
README.md
config/proxlb_example.yaml
proxlb/utils/proxmox_api.py

feature: Add a retry mechanism when connecting to the Proxmox API
Fixes: #157

feature: Add a retry mechanism when connecting to the Proxmox API

---

.github/workflows/30-pipeline-build-container-amd64.yml
.github/workflows/30-pipeline-build-container-arm64.yml

feature: Add workflows to build container images for AMD64 + ARM64 architecture
Fixes: #231

feature: Add workflows to build container images for AMD64 + ARM64 architecture

---

.changelogs/1.1.3/232_align_maintenance_mode_proxmox_ha.yml
.changelogs/1.1.3/release_meta.yml
proxlb/models/nodes.py

feature: Align maintenance mode with Proxmox HA maintenance mode
Requested-by: @ETES-Stuttgart
Fixes: #232

feature: Align maintenance mode with Proxmox HA maintenance mode

---

.changelogs/1.1.3/239_add_optional_delay_time_until_service_starts.yml
README.md
config/proxlb_example.yaml
proxlb/main.py
proxlb/utils/helper.py

feature: Add optional wait time before service action.
Fixes: #239

feature: Add optional wait time before service action.

---

.changelogs/1.1.3/241_make_amount_of_parallel_migrations_configurable.yml
README.md
config/proxlb_example.yaml
proxlb/models/balancing.py

feature: Make the amount of parallel migrations configurable
Fixes: #241

feature: Make the amount of parallel migrations configurable

---

README.md
docs/03_configuration.md

docs: Adjust docs regarding maintenance node hostnames
Fixes: #258

docs: Adjust docs regarding maintenance node hostnames

---

README.md

docs: Add compatibility matrix of tested Proxmox versions
Fixes: #273

docs: Add compatibility matrix of tested Proxmox versions

---

misc/01-replace-version.sh

feature: Add Helm chart support for ProxLB
Fixes: #281

feature: Add Helm chart support for ProxLB
